"""add user  Calender model

Revision ID: 268206c0cfa1
Revises: 19da35408259
Create Date: 2024-06-14 21:43:29.936726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268206c0cfa1'
down_revision: Union[str, None] = '19da35408259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calendar', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar', type_='foreignkey')
    op.drop_column('calendar', 'user_id')
    op.drop_column('calendar', 'created_at')
    # ### end Alembic commands ###
