"""add role in user table

Revision ID: 994c4ba9f33a
Revises: 54f0aa4dd29f
Create Date: 2024-05-12 18:11:53.704284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994c4ba9f33a'
down_revision: Union[str, None] = '54f0aa4dd29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_teacher')
    op.drop_column('users', 'is_student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_student', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_teacher', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
