services:
  api:
    container_name: school_api
    build:
      context: ./services/api
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
      - ./services/api:/srv/app
    environment:
      TZ: Asia/Tokyo
      DATABASE_NAME: 'school_db'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'root'
      DATABASE_HOST: 'localhost'
      DATABASE_PORT: '5433'
      EMAIL_IMAP_USERNAME: 'applicationcheckemail@gmail.com'
      EMAIL_IMAP_PASSWORD: 'egjlvuzxwysurwuq'
      EMAIL_IMAP_PORT: '993'
      EMAIL_IMAP_SSL: 'true'
      EMAIL_IMAP_HOST: 'smtp.gmail.com'
    networks:
      - school_app

  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static_volume:/app/static
    networks:
      - school_app

volumes:
  static_volume:

networks:
  school_app:
