
services:
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"  
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - school_app

volumes:
  db_data:

networks:
  school_app:
