"""Remove unique constraint from admin_id in groups table

Revision ID: 0960466b8cef
Revises: 9c34ba0115aa
Create Date: 2024-07-02 11:41:02.350566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0960466b8cef'
down_revision: Union[str, None] = '9c34ba0115aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_admin_id_key', 'groups', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('groups_admin_id_key', 'groups', ['admin_id'])
    # ### end Alembic commands ###
