"""Migration at 2024-08-09 11:50:12

Revision ID: 0e1c943e839d
Revises: 8f9e226adc48
Create Date: 2024-08-09 11:50:13.728465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1c943e839d'
down_revision: Union[str, None] = '8f9e226adc48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_settings', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_settings', 'language')
    # ### end Alembic commands ###
