"""add group icon in  group 

Revision ID: 286df726983a
Revises: b2ac33a54712
Create Date: 2024-07-02 10:20:14.366643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286df726983a'
down_revision: Union[str, None] = 'b2ac33a54712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_images', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'group_images')
    # ### end Alembic commands ###
