"""notification tbale and user notification

Revision ID: 2c2194e0fe37
Revises: 0489357561bf
Create Date: 2024-07-24 10:37:11.725539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c2194e0fe37'
down_revision: Union[str, None] = '0489357561bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('notifications', sa.Column('content', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'message')
    op.add_column('user_notifications', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_notifications_id'), 'user_notifications', ['id'], unique=False)
    op.drop_constraint('user_notifications_notification_id_fkey', 'user_notifications', type_='foreignkey')
    op.drop_constraint('user_notifications_user_id_fkey', 'user_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'user_notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_notifications', 'notifications', ['notification_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_notifications', type_='foreignkey')
    op.drop_constraint(None, 'user_notifications', type_='foreignkey')
    op.create_foreign_key('user_notifications_user_id_fkey', 'user_notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_notifications_notification_id_fkey', 'user_notifications', 'notifications', ['notification_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_notifications_id'), table_name='user_notifications')
    op.drop_column('user_notifications', 'is_read')
    op.drop_column('user_notifications', 'id')
    op.add_column('notifications', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('notification_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'timestamp')
    op.drop_column('notifications', 'content')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
