"""Migration at 2024-07-24 11:38:18

Revision ID: 34d83a6d7df7
Revises: 2c2194e0fe37
Create Date: 2024-07-24 11:38:19.436460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34d83a6d7df7'
down_revision: Union[str, None] = '2c2194e0fe37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_type', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('message', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'timestamp')
    op.drop_column('notifications', 'content')
    op.drop_index('ix_user_notifications_id', table_name='user_notifications')
    op.drop_constraint('user_notifications_user_id_fkey', 'user_notifications', type_='foreignkey')
    op.drop_constraint('user_notifications_notification_id_fkey', 'user_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'user_notifications', 'notifications', ['notification_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_notifications', 'id')
    op.drop_column('user_notifications', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_notifications', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_notifications', type_='foreignkey')
    op.drop_constraint(None, 'user_notifications', type_='foreignkey')
    op.create_foreign_key('user_notifications_notification_id_fkey', 'user_notifications', 'notifications', ['notification_id'], ['id'])
    op.create_foreign_key('user_notifications_user_id_fkey', 'user_notifications', 'users', ['user_id'], ['id'])
    op.create_index('ix_user_notifications_id', 'user_notifications', ['id'], unique=False)
    op.add_column('notifications', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'notification_type')
    # ### end Alembic commands ###
