"""store total like and comment

Revision ID: 4342c2529d2e
Revises: 318e6731eb74
Create Date: 2024-07-17 21:35:38.484814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4342c2529d2e'
down_revision: Union[str, None] = '318e6731eb74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('total_likes', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('total_comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'total_comments')
    op.drop_column('posts', 'total_likes')
    # ### end Alembic commands ###
