"""change school-info-to user

Revision ID: 55effff55aa9
Revises: 7ca3c69eb1fd
Create Date: 2024-07-25 17:32:20.092047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55effff55aa9'
down_revision: Union[str, None] = '7ca3c69eb1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'is_international_student')
    op.drop_column('user_profile', 'department')
    op.drop_column('user_profile', 'is_student')
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_student', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_international_student', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_international_student')
    op.drop_column('users', 'is_student')
    op.drop_column('users', 'department')
    op.add_column('user_profile', sa.Column('is_student', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('is_international_student', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
