"""Migration at 2024-08-08 19:02:51

Revision ID: 8f9e226adc48
Revises: 380acfde8811
Create Date: 2024-08-08 19:02:51.928525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9e226adc48'
down_revision: Union[str, None] = '380acfde8811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_otp', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_otp', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_otp', 'is_active')
    op.drop_column('user_otp', 'expires_at')
    # ### end Alembic commands ###
