"""make correct to admin user cna have more grpup 

Revision ID: 9c34ba0115aa
Revises: b0b590a05e39
Create Date: 2024-07-02 11:37:26.516161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c34ba0115aa'
down_revision: Union[str, None] = 'b0b590a05e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
