"""add reminder in calender

Revision ID: a2adb60d5b59
Revises: 318e6731eb74
Create Date: 2024-07-22 12:05:51.724938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2adb60d5b59'
down_revision: Union[str, None] = '318e6731eb74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('reminder_offset', sa.Integer(), nullable=True))
    op.add_column('calendar', sa.Column('is_reminder', sa.Boolean(), nullable=True))
    op.alter_column('calendar', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('calendar', 'is_reminder')
    op.drop_column('calendar', 'reminder_offset')
    # ### end Alembic commands ###
