"""Migration at 2024-09-19 20:13:05

Revision ID: b5a411ccba9e
Revises: 9aaa578fd648
Create Date: 2024-09-19 20:13:06.873278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a411ccba9e'
down_revision: Union[str, None] = '9aaa578fd648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_tokens_id'), 'notification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_notification_tokens_token'), 'notification_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_tokens_token'), table_name='notification_tokens')
    op.drop_index(op.f('ix_notification_tokens_id'), table_name='notification_tokens')
    op.drop_table('notification_tokens')
    # ### end Alembic commands ###
