"""Migration at 2024-09-19 20:44:08

Revision ID: bc9db4bce829
Revises: b5a411ccba9e
Create Date: 2024-09-19 20:44:09.646567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9db4bce829'
down_revision: Union[str, None] = 'b5a411ccba9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_tokens', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_tokens', 'is_active')
    # ### end Alembic commands ###
