"""Migration at 2024-08-07 14:13:19

Revision ID: c38e54a3cca8
Revises: 1be48b5c440a
Create Date: 2024-08-07 14:13:20.131930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38e54a3cca8'
down_revision: Union[str, None] = '1be48b5c440a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_events', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'school_events', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school_events', type_='foreignkey')
    op.drop_column('school_events', 'creator_id')
    # ### end Alembic commands ###
