"""Migration at 2024-09-14 10:02:01

Revision ID: c5f495e9be43
Revises: 9aaa578fd648
Create Date: 2024-09-14 10:02:02.324315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f495e9be43'
down_revision: Union[str, None] = '9aaa578fd648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_replies', sa.Column('parent_reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment_replies', 'comment_replies', ['parent_reply_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment_replies', type_='foreignkey')
    op.drop_column('comment_replies', 'parent_reply_id')
    # ### end Alembic commands ###
