"""post comment like entity 

Revision ID: c8bcb49dcb3e
Revises: 6dc35da108d1
Create Date: 2024-06-20 21:28:31.466464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bcb49dcb3e'
down_revision: Union[str, None] = '6dc35da108d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
