"""Migration at 2024-09-21 10:48:27

Revision ID: db9305a5062b
Revises: e112c7565a3d
Create Date: 2024-09-21 10:48:28.426907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9305a5062b'
down_revision: Union[str, None] = 'e112c7565a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_notification', 'notification_reads', ['user_id', 'notification_id'], unique=False)
    op.create_index(op.f('ix_notification_reads_id'), 'notification_reads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_reads_id'), table_name='notification_reads')
    op.drop_index('idx_user_notification', table_name='notification_reads')
    op.drop_table('notification_reads')
    # ### end Alembic commands ###
