"""Migration at 2024-08-08 11:43:09

Revision ID: dbf38ab51636
Revises: c38e54a3cca8
Create Date: 2024-08-08 11:43:10.591247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf38ab51636'
down_revision: Union[str, None] = 'c38e54a3cca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_profile_searchable', sa.Boolean(), nullable=True),
    sa.Column('is_message_notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_post_notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_survey_notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_two_factor_authentication_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_settings')
    # ### end Alembic commands ###
