"""Migration at 2024-08-28 08:43:18

Revision ID: df0bbf5d0ced
Revises: 0e1c943e839d
Create Date: 2024-08-28 08:43:18.985883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0bbf5d0ced'
down_revision: Union[str, None] = '0e1c943e839d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_student', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
