"""Migration at 2024-09-21 09:42:17

Revision ID: e112c7565a3d
Revises: bc9db4bce829
Create Date: 2024-09-21 09:42:18.048811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e112c7565a3d'
down_revision: Union[str, None] = 'bc9db4bce829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('possible_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'possible_url')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
